Repository ember-cli/ember-template-imports, pull requests merged in 2022-10, with the labels that each got.

#54 Fix build failures due to backticks within in template tags
  __tests__/preprocess-embedded-templates.test.ts
  src/preprocess-embedded-templates.ts
  tests/integration/gjs-test.gjs
Labels: bug

#56 internal: set up Dependabot
  .github/dependabot.yml
Labels: internal

#73 Do not require parent addon to include ember-cli-htmlbars
  ember-addon-main.js
Labels: enhancement

#74 Provide the contents of the parsed template when calling `parseTemplates`
  __tests__/parse-templates.test.ts
  src/parse-templates.ts
Labels: enhancement

#77 feat: move over utils from ember-template-lint
  src/util.js
Labels: internal

#75 chore: converts util to typescript
  __tests__/preprocess-embedded-templates.test.ts
  package.json
  src/babel-plugin.js
  src/parse-templates.ts
  src/preprocessor-plugin.js
  src/template-literal-transform.js
  src/template-tag-transform.js
  src/util.d.ts
  src/util.js
  src/util.ts
  yarn.lock
Labels: internal

#78 Bring back `src/utils.js` temporarily
  .eslintignore
  src/util.js
Labels: bug
