Repository ember-cli/ember-template-imports, pull requests merged in 2023-10, with the labels that each got.

#193 bump minimum ember-cli-htmlbars
  package.json
  yarn.lock
Labels: dependencies

#176 fix: add eslint-plugin-ember support version
  README.md
Labels: documentation

#146 [Cleanup] Remove all traces of hbs
  README.md
  __tests__/parse-templates.test.ts
  __tests__/preprocess-embedded-templates.test.ts
  package.json
  src/babel-plugin.js
  src/parse-templates.ts
  src/preprocess-embedded-templates.ts
  src/preprocessor-plugin.js
  src/template-literal-transform.js
  src/util.ts
  tests/dummy/app/components/hbs-test.js
  tests/dummy/app/templates/application.hbs
  tests/integration/.gitkeep
  tests/integration/hbs-test.js
Labels: breaking

#198 upgrade ember-auto-import
  package.json
  yarn.lock
Labels: dependencies

#187 Use content-tag, which fixes *all the bugs*
  .eslintrc.js
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  __tests__/parse-templates.test.ts
  __tests__/preprocess-embedded-templates.test.ts
  ember-addon-main.js
  ember-cli-build.js
  jest.config.js
  local-types/parse-static-imports.d.ts
  package.json
  pnpm-lock.yaml
  src/babel-plugin.js
  src/debug.ts
  src/index.ts
  src/parse-templates.ts
  src/preprocess-embedded-templates.ts
  src/preprocessor-plugin.js
  src/template-tag-transform.js
  src/util.js
  src/util.ts
  tests/dummy/app/components/.gitkeep
  tests/dummy/app/controllers/.gitkeep
  tests/dummy/app/helpers/.gitkeep
  tests/dummy/app/models/.gitkeep
  tests/dummy/app/routes/.gitkeep
  tests/dummy/app/templates/application.hbs
  tests/helpers/.gitkeep
  tests/unit/.gitkeep
  tsconfig.json
Labels: enhancement, breaking

#209 Remove unused dependencies as well as template-lint
  .github/workflows/ci.yml
  .template-lintrc.js
  package.json
  pnpm-lock.yaml
Labels: internal

#210 Upgrade and fix lint deps
  .eslintignore
  .eslintrc.js
  .prettierignore
  ember-addon-main.js
  package.json
  pnpm-lock.yaml
Labels: internal
