Repository ember-cli/ember-template-imports, pull requests merged in 2024-09, with the labels that each got.

#241 add back toc names for inspector
  .eslintrc.js
  .npmignore
  ember-addon-main.js
  package.json
  pnpm-lock.yaml
  src/babel-plugin.js
  tests-babel/transform.test.js
  tests/integration/gjs-test.gjs
Labels: bug

#244 run babel tests in ci & rm module name
  .github/workflows/ci.yml
  src/babel-plugin.js
  tests-babel/transform.test.js
  tests/integration/gjs-test.gjs
Labels: bug, internal

#245 Pin volta toolchain for local usage
  package.json
Labels: internal

#247 Move local tooling to pnpm 9
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
Labels: internal

#251 Add import path for uniqueId helper
  README.md
Labels: documentation
